### ISSUE TITLE
Problems with PHP 7.4

### ISSUE THREAD

**Issue by tomasnorre** [helhum/ter-client#11]
Hi, 

I encountered a problem today with the ter-client and PHP 7.4.
```
PHP Fatal error:  Uncaught Error: Class 'SoapClient' not found in $HOME/.composer/vendor/helhum/ter-client/src/Connection.php:27
Stack trace:
#0 $HOME/.composer/vendor/helhum/ter-client/src/Cli/Command/UploadCommand.php(93): Helhum\TerClient\Connection::create()
#1 $HOME/.composer/vendor/symfony/console/Command/Command.php(255): Helhum\TerClient\Cli\Command\UploadCommand->execute()
#2 $HOME/.composer/vendor/symfony/console/Application.php(987): Symfony\Component\Console\Command\Command->run()
#3 $HOME/.composer/vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand()
#4 $HOME/.composer/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun()
#5 $HOME/.composer/vendor/helhum/ter-client/ter-client(15): Symfony\Component\Console\Application->run()
#6 {main}
  thrown in $HOME/.composer/vendor/helhum/ter-client/src/Connection.php on line 27
```
Switching back to PHP 7.2 it worked instantly.

**Comment by spoonerWeb** [comment]
Looks like the Soap php module isn't loaded with 7.4?

**Comment by tomasnorre** [comment]
I think you're right.. Doh.

**Comment by tomasnorre** [comment]
Ws the case my bad, sorry.
